django/pjt01/movies/urls.py
from django.urls import path
from  . import views

app_name = 'movies'

urlpatterns = [
    path('',views.index, name='index'),
    path('new/',views.new, name='new'), #new에 db에 data 넣는 것 :restful(create))
    path('<int:pk>/',views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

django/pjt01/pjt01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #새로운 path
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

django/pjt01/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=30)
    title_en = models.CharField(max_length=40)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=20)
    watch_grade = models.CharField(max_length=20)
    score = models.FloatField()
    poster_url = models.TextField()
    description =  models.TextField()

django/pjt01/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie

# Create your views here.
def index(request):
    #db에서 모든 인스턴스 가져오기
    #1. 모든 movies 가져오기
    movies = Movie.objects.all()

    #2. context 생성
    context = {
        'movies': movies,
    }

    #2. context와 함께 render하기
    return render(request, 'movies/index.html', context)


def new(request):
    if request.method == 'POST':
    #db의 create(request라는 변수에 다 들음)
        title = request.POST.get('title')
        title_en = request.POST.get('title_en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch_grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')

        movie = Moive.objects.create(
            title=title,
            title_en=title_en,
            audience=audience,
            open_date=open_date,
            genre=genre,
            watch_grade=watch_grade,
            score=score,
            poster_url=poster_url,
            description=description
        )

        return redirect('movide:detail', movie.pk)

    else:
        return render(request, 'movies/new.html')

def detail(request, pk):
    Moive.objects.get(pk=pk)
    context={
        'movie':movie,
    }
    return render(request, 'movies/detail.html')

def edit(request, pk): #수정하는 걸 보여주는 페이지랑, 수정하는 페이지
    movie=Movie.objects.get(pk=pk)

    if request.method =='POST':
        title = request.POST.get('title')
        title_en = request.POST.get('title_en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch_grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')

        movie.title=title
        movie.title_en=title_en
        movie.audience=audience
        movie.open_date=open_date
        movie.genre=genre
        movie.watch_grade=watch_grade
        movie.title=title
        movie.score=score
        movie.poster_url=poster_url
        movie.description=description
        movie.save()

        return redirect('movies:detail',movie.pk)

    else :
        context ={
            'movie':movie,
        }
    return render(request,'movies/edit.html',context)


def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')

django/pjt01/movies/templates/movies/detail.html
{% extends 'base.html '%}
{% block body%}

<h1> movie detail</h1>
<img src="{{movie.poster_url}}" alt="poster" width="300px">
<ul>
    <li><b>Title: </b> {{movie.title}}<</li>
    <li><b>title_en: </b> {{movie.title_en}}<</li>
    <li><b>audience: </b> {{movie.audience}}<</li>
    <li><b>open_date: </b> {{movie.open_date}}<</li>
    <li><b>genre: </b> {{movie.genre}}<</li>
    <li><b>watch_grade: </b> {{movie.watch_grade}}<</li>
    <li><b>score: </b> {{movie.score}}<</li>
    <li><b>poster_url: </b> {{movie.poster_url}}<</li>
    <li><b>description: </b> {{movie.description}}<</li>
</ul>

<a href="{% url 'movies:index' %}">목록</a>
<a href="{% url 'movies:edit' movie.pk %}">수정</a>
<a href="{% url 'movies:delete' movie.pk %}">삭제</a>

{% endblock %}

django/pjt01/movies/templates/movies/edit.html
{% extend 'base.html'%}

{%block body%}
<form action="" method="POST"> <!--action 비어있는 건 나 자신으로 -->
{% csrf_token %}
    <div>
        <label for = "">title : </label>
        <input type="text" name="title" value="{{movie.title}}">
    </div>
    <div>
        <label for = "">title en: </label>
        <input type="text" name="title_en" value="{{movie.title_en}}">
    </div>
    <div>
        <label for = "">audience: </label>
        <input type="number" name="audience" value="{{movie.audience}}">
    </div>
    <div>
        <label for = "">open date: </label>
        <input type="date" name="open_date" value="{{movie.open_date|date:'Y-m-d'}}">
    </div>
    <div>
        <label for = "">genre: </label>
        <input type="text" name="genre" value="{{movie.genre}}">
    </div>
    <div>
        <label for = "">watch grade: </label>
        <input type="text" name="watch_grade" value="{{movie.watch_grade}}">
    </div>
    <div>
        <label for = "">score: </label>
        <input type="number" name="score" step="0.01" min="0" max="10" value="{{movie.score}}"><!--몇단위로 올라갈지-->
    </div>
    <div>
        <label for = "">poster url: </label>
        <input type="text" name="poster_url" value="{{movie.poster_url}}">
    </div>
    <div>
        <label for = "">description: </label>
        <textarea name="description" >{{movie.description}} </textarea>
    </div>
    <div>
        <input type="submit">
    </div>
</form>

{% endblock %}

django/pjt01/movies/templates/movies/index.html
{% extends 'base.html'%}

{% block body %}

<h1> movie index</h1>

<a href="{%url movies:new%}">새 영화 등록</a>
<ul>
    {%for movie in movies%}
        <li>
        <a href="url 'movies:detail' movie.pk"><{{movie.title}} - {{movie.score}}</a>
        </li>
    {% endfor %}
</ul>

{% endblock %}

django/pjt01/movies/templates/movies/new.html
{% extends 'base.html'%}

{% block body %}

<h1> new movie</h1>

<form action="" method="POST"> <!--action 비어있는 건 나 자신으로 -->
{% csrf_token %}
    <div>
        <label for = "">title : </label>
        <input type="text" name="title">
    </div>
    <div>
        <label for = "">title en: </label>
        <input type="text" name="title_en">
    </div>
    <div>
        <label for = "">audience: </label>
        <input type="number" name="audience">
    </div>
    <div>
        <label for = "">open date: </label>
        <input type="date" name="open_date">
    </div>
    <div>
        <label for = "">genre: </label>
        <input type="text" name="genre">
    </div>
    <div>
        <label for = "">watch grade: </label>
        <input type="text" name="watch_grade">
    </div>
    <div>
        <label for = "">score: </label>
        <input type="number" name="score" step="0.01" min="0" max="10"><!--몇단위로 올라갈지-->
    </div>
    <div>
        <label for = "">poster url: </label>
        <input type="text" name="poster_url">
    </div>
    <div>
        <label for = "">description: </label>
        <textarea name="description"> </textarea>
    </div>
    <div>
        <input type="submit">
    </div>
</form>

{%endblock%}

django/pjt01/pjt01/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body> 
    {%block body%}
    {%endblock%}
</body>
</html>