django/crud/articles/urls.py
from django.urls import path
from . import views

#새로운 변수
app_name = 'articles'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('new/', views.new, name = 'new'), #데이터를 입력받아서 다른 페이지로 넘기는 것 # GET,POST /articles/new/
    #path('create/', views.create, name = 'create'),  #RESTful하지는 않음(x) 
    #layout은 같은데 컨텐츠만 바뀌게 하는 것/ variable routing/ 게시글을 구분할 수 있는 colum ->id
    path('<int:pk>/', views.detail, name = 'detail'),
    path('<int:pk>/edit/', views.edit, name = 'edit'),#수정하는 양식이 있는 페이지
   # path('<int:pk>/update/', views.update, name = 'update'),
    path('<int:pk>/delete/', views.delete, name = 'delete'),
]

#URL Name -> 각각의 path
#path('주소/', views.함수, name='이름' )
# {% url 'url 이름' %} => /students/new/
# [장점]
# 1. 주소의 변경이 필요할 때, urls.py에서만 수정해주면 됨.
# 2. 마지막 '/'를 빼먹는 실수를 차단할 수 있음.

#APP Name - 특정 app의 urls.py 자체
# {% url 'articles:index'%}
# {% url 'app_name:path_name'%}

#RESTful

#Django는 PUT/PATCH/DELETE 불가능하기에
#GET /articles/2/edit #=> 수정 페이지 보여줌
#POST /articles/edit #=> 수정 작업 수행
#웹프레임워크는 두 메소드를 다르게 받아드림. 구분.

#ex)
#GET /users/1 유저1번 가져옴
#PUT /users/1 유저1번 수정
#DELETE /users/1 유저1번 삭제

django/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

django/crud/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    #3개의 colum 'title, content, created_at
    #id = models.AutoField(priary_key=True)
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True) #데이터가 생긴 시간 옵션
    updated_at = models.DateTimeField(auto_now=True)#수정될때마다 시간추가

    def __str__(self): #매직 매서드(특수 목적 메소드)/스트링으로 리턴해야함.
        return f'{self.id}번 글 - {self.title} : {self.content}'
    # str(article), print(article),


    #1. models.py 작성/수정
    #2. 명령어 python manage.py makemigrations 
    #=> models.py 바탕으로 설계도 생성
    #3. python manage.py  migrate
    #=> 실제 DB(db.sqlite3)에 설계도를 적용

    #DB에 데이터를 생성하는 방법 3가지
    #1. article=Article()
    #   article.title='첫번째'
    #   article.content='내용'
    #   article.save()

    #생성자를 이용해서 (models.Model이 들고 있음)
    #2. article2=Article(title='2',content='_2_')
    #   article2.save()

    #3. article3 = 

    #READ
    #1. All - Article.objects.all() #여러개 나옴(queryset), 복수(쿼리스트링)
    
    #2. 1개 - Article.objects.get(id=1) get쓸때는 id로 검색하자.
    #get은 id가 무슨값인지, 단수(인스턴스) 
    #1)unique한 colum로 된 것으로 하는 것이 좋음.
    #2)not null인 컬럼으로 한다.
    
    #3. 조건 - Article.objects.filter(title='세번째') #복수로 리턴됨.
    # WHERE

    #4-1. QuerySet + .first(), .last() #단수
    #4-2. .order_by() 가져온 데이터를 정렬 할 수 있음.
    #   Article.objects.all().order_by('title') #오름차순
    #   Article.objects.all().order_by('-title') #내림차순
    #4-3. offset, limit (OFFSET, LIMIT) [offset:offset+limit]
    #   Article.objects.all()[1:2] #=> [2] [1:3] =>[2, 3]

    #UPDATE 수정하고자하는 데이터가 있어야함.
    #값을 할당하고 DB에 반영해줘야함. 
    #1.데이터를 가져오기: a = Article.objects.get(id=1)
    #2.수정할 값 할당하기: a.title='first!'
    #3.저장하기 (db에 반영하기): a.save()

    #DELETE
    #1. 데이터 가져오기 - a = Article.objects.get(id=1)
    #2. 삭제하기 (DB에 반영) - a.delete()
    

django/crud/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all().order_by('-id') #자료형 queryset
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/index.html',context)

def new(request):
    if  request.method == 'POST': #=> 'GET' 'POST' 담겨있음. string으로 담김.
    # student를 생성함 (def create)
    title=request.POST.get('title')
    content=request.POST.get('content')
    article = Article.objects.create(title=title, content=content)
    article.save()
    return redirect('articles:detail',article.pk)

    else :
    #new page를 보여주면 됨.
    return render(request, 'articles/new.html')

# def create(request): #post 요청을 받음
#     #넘어온 데이터 받기
#     #이유2번 - POST(http body)라는 것을 통해 넘어옴
#     #title=request.GET.get('title')
#     #content=request.GET.get('content')
#     title=request.POST.get('title')
#     content=request.POST.get('content')

#     #새로운 글을 쓰는 부분, article에는 뭐가 들어갈까? 게시글인스턴스
#     # article.title
#     # article.content
#     article = Article.objects.create(title=title, content=content)

#     #return render(request, 'articles/create.html',context)
#     #다른 곳으로 요청을 한다. 다른 곳으로 연결을 한다. get요청을 받는 페이지로 돌려 보내야함.
#     #return redirect(f'/articles/{article.pk}/')
#     return redirect('articles:detail',article.pk)

def detail(request, pk): #parameter 적어줘야함.
    #1개만 찾아 올 것임.
    #Article.objects.get(id=pk)
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request,'articles/detail.html',context)

def delete(request, pk):
    if request.method =='POST':
        article = Article.objects.get(pk=pk)
        article.delete()
        return redirect('articles:index')

def edit(request, pk):
        #1. pk에 해당하는 article 가져오기
        article = Article.objects.get(pk=pk)
    if request.method=="POST":
        #2. update로 데이터를 넘기는 것.
        title = request.POST.get('title')
        content = request.POST.get('content')

        #3. edit로부터 넘어온 데이터 가져오기
        article.title=title
        article.content=content
        article.save()

        return redirect(f'/articles/{article.pk}/') #detail페이지로 리다이렉트
    else:
        article = Article.objects.get(pk=pk)
        context = {
        'article': article,
        }
        return render(request, '/articles/edit.html', context)

# def update(request, pk):
#     #1. pk에 해당하는 article 가져오기
#     article = Article.objects.get(pk=pk)
#     #2. update로 데이터를 넘기는 것.
#     title = request.POST.get('title')
#     content = request.POST.get('content')

#     #3. edit로부터 넘어온 데이터 가져오기
#     article.title=title
#     article.content=content
#     article.save()

#     return redirect(f'/articles/{article.pk}/') #detail페이지로 리다이렉트

     

django/crud/articles/templates/articles/create.html
<!--넘어온 데이터를 보여주기-->
<!--넘어온 데이터 받기-->

{% extends 'base.html'%}
{% block body %}

<h1>CREATE</h1>
<h2>{{title}}</h2>
<p>{{content}}</p>

{%endblock%}

django/crud/articles/templates/articles/detail.html
{% extends 'base.html'%}

{%block body%}
<h1>Article detail</h1>

<h2>{{article.title}}</h2>
<p>{{article.content}}</p>
<h5>{{article.created_at}}</h5>s
<h5>{{article.updated_at}}</h5>

<!--<a href="/articles/{{article.pk}}/edit/">수정</a>
<a href="/articles/{{article.pk}}/delete/">삭제</a>
<a href="/articles">Index로</a>-->
<a href="{%url 'articles:index'}">LIST</a>
<a href="{%url 'articles:edit' article.pk%}">edit</a>
<a href=>delete</a>
<!-- 태그 POST 요청을 보낼 수 없습니다. 그렇다면 form tag! 삭제하는 부분 form으로 변경하고 메소드에 post넣어서
어떻게 post요청하는 지?-->
<form action="{%url 'articles:delete' article.pk%}" method="POST">
    {%crsf_token%}
    <input type="submit" value="Delete">
</form>
{%endblock%}

django/crud/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block body %}

<h1>Edit Article</h1>
<!--<form action="/articles/{{article.pk}}/update/", method="POST"> -->
<!--#{% url 'articles:update' article.pk%}#-->
<form action="", method="POST"> 
{% csrf_token %}
<label for="">Title: </label>
<!--input tag에만 해당함 value-->
<input type="text" name="title" value="{{article.title}}">
<label for="">Content: </label>
<input type="text" name="content" value="{{article.content}}">
<!--textarea는 vaule안되고 
<textarea type="text" name="title">{{article.title}}</textarea>
-->
<input type="submit">
</form>

{% endblock %}

django/crud/articles/templates/articles/index.html
<!--전체 게시글 보는 리스트 페이지-->
{% extends 'base.html'%}
{% block body %}

<h1>ARTICLE INDEX</h1>
<!--link 만드는 태그 a-->
<!--주소를 대체할 수 있는 것
<a href="/articles/new/">NEW ARTICLE</a>-->
<a href = "{ %url 'articles:new'% }"></a>
<ul>
    {% for article in articles %}
    <li>
    <!--    <a href="/articles/{{ article.pk }}/">{{article.title}}</a>--> <!--클릭 할 수 있도록-->
        <a href="{% url 'articles:detail' article.pk%}">{{article.title}}</a> <!--클릭 할 수 있도록-->
    </li>
    {% endfor %}
</ul>
{%endblock%}

django/crud/articles/templates/articles/new.html
<!--Form Tag를 사용하여, receive로 데이터 보내기-->
<!--title, content-->
{%extends 'base.html'%}
{% block body%}
<h1>NEW ARTICLE</h1>
<!--
<form action="/articles/create/", method="GET"> 
-->
<!--GET이 아닌 POST를 써야하는 이유-->
<!--1. GET의 의마상 맞지 않다.-->
<!--2. 데이터가 URL에 노출되면 안되기 때문에(보안)-->
<!--F5로 게시글이 생기는 것을 방지하기 위함-->
<!--CREATE로 보낸 요청은 DB에 생성되는 것이기에 최소한의 신원 확인이 필요 (CSRF)-->
<!--<form action="/articles/create/", method="POST">
#{% url 'articles:screate' %}#
--> 
<form action="", method="POST"> <!--액션에 없으면 자기자신-->
{% csrf_token %}
<label for="">Title: </label>
<input type="text" name="title">
<label for="">Content: </label>
<input type="text" name="content">
<input type="submit">
</form>
{%endblock%}